const dater = require('./index')

console.log("格式化日期对象：", dater.format(new Date()))
console.log("-----------------------------------------")
console.log("当前时间：", dater.getNowTime())
console.log("-----------------------------------------")
console.log("根据字符串获取日期对象：", dater.getDateByString('2020-03-03'))
console.log("-----------------------------------------")
console.log("获得某月的天数：", dater.getMonthDays(2, 2020))
console.log("-----------------------------------------")
console.log("今天：", dater.getDateRange(0, 'day'))
console.log("-----------------------------------------")
console.log("昨天：", dater.getDateRange(-2, 'day'))
console.log("-----------------------------------------")
console.log("最近7天：", dater.getDateRange(-7, 'day'))
console.log("-----------------------------------------")
console.log("最近30天：", dater.getDateRange(-30, 'day'))
console.log("-----------------------------------------")
console.log("本周：", dater.getDateRange(0, 'week'))
console.log("-----------------------------------------")
console.log("上周：", dater.getDateRange(-1, 'week'))
console.log("-----------------------------------------")
console.log("本月：", dater.getDateRange(0, 'month'))
console.log("-----------------------------------------")
console.log("上月：", dater.getDateRange(-1, 'month'))
console.log("-----------------------------------------")
console.log("获取星期几：", dater.getWeekForDay('2020-03-03'))